#!/usr/bin/perl

# Generate grep'able contact info files from Netdot
# 
#
#
use strict;
use lib "<<Make:LIB>>";
use Netdot::DBI;
use Data::Dumper;

my $DIR = "<<Make:PREFIX>>/export";
my $DEBUG = 0;

my @files = ( "$DIR/contacts.txt" );

foreach my $f (@files){
    
    open (FILE, ">$f") 
	or die "Couldn't open $f: $!\n";
    select (FILE);
    
    print "            ****        THIS FILE WAS GENERATED FROM A DATABASE         ****\n";
    print "            ****           ANY CHANGES YOU MAKE WILL BE LOST            ****\n";
    print "\n  Generated by $0 on ", scalar(localtime), "\n\n\n";
    
    my @cls = sort { $a->name cmp $b->name } ContactList->retrieve_all;
    
    foreach my $cl (@cls){
	my @sites    = $cl->sites;
	my @entities = $cl->entities;
	my @contacts = $cl->contacts;
	my @people = map { $_->person } @contacts;
	my @people = sort { $a->lastname cmp $b->lastname } @people;
	
	foreach my $site (@sites){
	    my $prefix = $site->name;
	    &print_people($prefix, \@people);
	}
	foreach my $ent (@entities) {
	    my $prefix = $ent->name;
	    &print_people($prefix, \@people);
	}
    }
    close (FILE);
}

sub print_people {
    my ($prefix, $people) = @_;
    foreach my $person ( @$people ){
	my $pref = $prefix;
	$pref .= ": " . $person->firstname . " " . $person->lastname;
	print $pref, ": Employer: ", $person->entity->name, "\n" if ($person->entity);
	print $pref, ": Position: ", $person->position, "\n" if ($person->position);
	print $pref, ": Office: ", $person->office, "\n" if ($person->office);
	print $pref, ": Email: <", $person->email, ">\n" if ($person->email);
	print $pref, ": Cell: ", $person->cell, "\n" if ($person->cell);
	print $pref, ": Pager: ", $person->pager, "\n" if ($person->pager);
	print $pref, ": Email-Pager: ", $person->emailpager, "\n" if ($person->emailpager);
    }
}
