#!/usr/bin/perl

# Generate grep'able contact info files from Netdot
# 
#
#
use strict;
use lib "PREFIX/lib";
use Netdot::DBI;
use Data::Dumper;

my $DIR = "/usr/local/netdot/export";
my $DEBUG = 0;

my @files = ( "$DIR/building-contacts.txt" );

foreach my $f (@files){
    
    open (FILE, ">$f") 
	or die "Couldn't open $f: $!\n";
    select (FILE);
    
    my (@sites, @contacts, @people);
        
    unless ( @sites = Site->retrieve_all() ){
	die "No sites found in db\n";
    }
    
    print "            ****        THIS FILE WAS GENERATED FROM A DATABASE         ****\n";
    print "            ****           ANY CHANGES YOU MAKE WILL BE LOST            ****\n";
    print "\n  Generated by $0 on ", scalar(localtime), "\n\n\n";
    
    @sites = sort { $a->name cmp $b->name } @sites;
    
    foreach my $site (@sites){
	unless ( $site->contactlist ){
	    next;
	}
	@contacts = $site->contactlist->contacts;
	@people = map { $_->person } @contacts;
	@people = sort { $a->lastname cmp $b->lastname } @people;
 	
	foreach my $person ( @people ){
	    my $prefix = $site->name . ": " . $person->entity->name . ": " . $person->firstname . " " . $person->lastname;
	    print $prefix, ": Position: ", $person->position, "\n" if ($person->position);
	    print $prefix, ": Office: ", $person->office, "\n" if ($person->office);
	    print $prefix, ": Email: <", $person->email, ">\n" if ($person->email);
	    print $prefix, ": Cell: ", $person->cell, "\n" if ($person->cell);
	    print $prefix, ": Pager: ", $person->pager, "\n" if ($person->pager);
	    print $prefix, ": Email-Pager: ", $person->emailpager, "\n" if ($person->emailpager);
	}
    }

    close (FILE);
}
