#!/usr/bin/perl
#
# insert sample data
#

use strict;

my $DB_HOME = "/usr";
my $BINDIR = "$DB_HOME/bin";
my $TMP = "./.tmp";

open (TMP, ">$TMP")
    or die "Can't open $TMP: $!\n";

# INSERT INTO Meta (name) VALUES ( 'Meta' );  

print TMP <<END;
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description) 
  VALUES ( 'Address', 'street1', 'street1,street2,pobox,city,state,zip,country,info', 'street1,street2,city,state,zip', '', 'sites:Site:address,persons:Person:address' , '1', 'Street, City, etc.');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description) 
 VALUES ( 'Address_history', 'modified', 'modified,modifier,street1,street2,pobox,city,state,zip,country,info', 'modified,modifier,street1,street2,city', '', 'sites:Site:address,persons:Person:address' , '1', 'Street, City, etc.');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description) 
  VALUES ('Availability', 'name', 'name,info', 'name,info', '', 'sites:Site:availability,persons:Person:availability,entities:Entity:availability', '1','Timeframe in which a person or site is available for problem notifications');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description) 
  VALUES ('Circuit', 'cid', 'cid,connection,status,nearend,farend,type,speed,dlci,installdate,vendor,info', 'cid,connection,nearend,farend,type,vendor,status', 'type:CircuitType,nearend:Interface,farend:Interface,connection:Connection,vendor:Entity,status:Status', '', '1', 'A WAN circuit provided by a third party');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description) 
  VALUES ('CircuitType', 'name', 'name,info', 'name,info', '', 'circuits:Circuit:type', '1', 'Types of WAN circuits');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description) 
  VALUES ('Connection', 'name', 'name,entity,nearend,farend,info', 'name,entity,nearend,farend', 'nearend:Site,farend:Site,entity:Entity', 'circuits:Circuit:connection', '1', 'Link between two sites.  A connection can consist of one or more circuits');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description) 
  VALUES ('Contact', 'email', 'contacttype,contactlist,person,email,office,cell,home,pager,emailpager,fax,info', 'email,contacttype,person,office,cell', 'contactlist:ContactList,contacttype:ContactType,person:Person', '', '1', 'Contact Information');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description)
  VALUES ('ContactList', 'name', 'name,info', 'name,info', '', 'contacts:Contact:contactlist,entities:Entity:contactlist,nodes:Node:contactlist,sites:Site:contactlist', '1', 'A list of contacts');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description) 
  VALUES ('ContactType', 'name', 'name,info', 'name', '', 'contacts:Contact:contacttype', '1', 'Type of contact');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description)
  VALUES ('Entity', 'name', 'name,aliases,type,availability,contactlist,acctnumber,autsys,bgppeerip,info', 'name,type', 'contactlist:ContactList,availability:Availability,type:EntityType', 'connections:Connection:entity,sites:EntitySite:entity,nodes:Node:vendor,models:Model:manufacturer,subnets:Subnet:entity', '1', 'An organization related to the network in some way');
INSERT INTO Meta (name, columnorder, linksto, linksfrom, mainobject, description)
  VALUES ('EntitySite', 'entity,site', 'entity:Entity,site:Site', '', '0','A relationship linking an Entity with a physical Site');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description)
  VALUES ('EntityType', 'name', 'name,info', 'name', '', 'entities:Entity:type', '1', 'Types of Entities');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description)
  VALUES ('Interface', 'ifdescr', 'ifdescr,node,ifalias,ifindex,iftype,ifspeed,ifadminstatus,physaddr,jacknumber,info,managed', 'ifdescr,node,physaddr,ifadminstatus,jacknumber', 'node:Node', 'ips:Ip:interface,parents:InterfaceDep:child,children:InterfaceDep:parent,nearcircuits:Circuit:nearend,farcircuits:Circuit:farend', '1', 'An interface associated with a node');
INSERT INTO Meta (name, columnorder, linksto, linksfrom, mainobject, description)
  VALUES ('InterfaceDep', 'parent,child', 'parent:Interface,child:Interface', '', '0', 'Dependency relationship between two interfaces. Provides a basis for topology information');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description)
  VALUES ('Ip', 'address', 'address,mask,interface,subnet', 'address,mask,interface', 'interface:Interface,subnet:Subnet', 'names:Name:ip', '1', 'An IP Address associated with an Interface');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description)
  VALUES ('Model', 'name', 'name,manufacturer,info', 'name,manufacturer', 'manufacturer:Entity', 'nodes:Node:model', '1', 'A devices manufacturer model');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description)
  VALUES ('Name', 'name', 'name,ip', 'name,ip', 'ip:Ip', '', '1', 'A DNS name associated with an IP address');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description)
  VALUES ('Node', 'name', 'name,aliases,type,model,sysdescription,physaddr,serialnumber,site,room,rack,dateinstalled,sw_version,contactlist,oobname,oobnumber,vendor,info,managed', 'name,type,model,site,room', 'site:Site,vendor:Entity,contactlist:ContactList,type:NodeType,model:Model', 'interfaces:Interface:node,services:NodeService:node', '1', 'A network device');
INSERT INTO Meta (name, columnorder, linksto, linksfrom, mainobject, description)
  VALUES ('NodeService', 'node,service', 'node:Node,service:Service', '', '0', 'A relationship linking a host with a running Internet service');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description)
  VALUES ('NodeType', 'name', 'name,info', 'name,info', '', 'nodes:Node:type', '1', 'Types of network devices');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description) 
  VALUES ('Person', 'lastname', 'lastname,firstname,aliases,position,department,address,availability,info', 'lastname,firstname,position,department', 'address:Address,availability:Availability', 'contactinfo:Contact:person', '1', 'Information about an individual');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description)
  VALUES ('Service', 'name', 'name,info', 'name', '', 'nodes:NodeService:service', '1', 'An Internet service running on a host');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description)
  VALUES ('Site', 'name', 'name,aliases,address,availability,contactlist,info', 'name,address', 'address:Address,availability:Availability,contactlist:ContactList', 'nearconnections:Connection:nearend,farconnections:Connection:farend,entities:EntitySite:site,nodes:Node:site', '1', 'A Physical location');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description)
  VALUES ('Status', 'name',  'name,info', 'name', '', 'circuits:Circuit:status', '1', 'Circuit status');
INSERT INTO Meta (name, label, columnorder, columnorderbrief, linksto, linksfrom, mainobject, description)
  VALUES ('Subnet', 'address', 'address,prefix,entity,info', 'address,prefix,entity', 'entity:Entity', 'ips:Ip:subnet', '1', 'A network subnet');

END

system ("$BINDIR/mysql --user=root netdot < $TMP");

close(TMP);
system ("rm -f $TMP");
