#!/usr/bin/perl -w
use strict;

my $PREFIX = $ARGV[0] or die "Need install prefix\n";

# Miscellaneous upgrade-related tasks


###########################################################
# Run system commands
sub cmd {
    my $str = shift;
    if ( system($str) != 0 ){
	die "There was a problem running $str\n";
    }
}
