# This Makefile is for the SNMP::Info extension to perl.
#
# It was generated automatically by MakeMaker version
# 6.44 (Revision: 54639) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#
#   MakeMaker Parameters:

#     ABSTRACT_FROM => q[Info.pm]
#     AUTHOR => q[Eric A. Miller <emiller@cpan.org>]
#     LICENSE => q[bsd]
#     NAME => q[SNMP::Info]
#     PMLIBDIRS => [q[Info]]
#     PREREQ_PM => { Test::More=>q[0], Math::BigInt=>q[0], SNMP=>q[0] }
#     VERSION_FROM => q[Info.pm]
#     clean => { FILES=>q[SNMP-Info-*] }
#     dist => { COMPRESS=>q[gzip -9f], SUFFIX=>q[gz] }
#     realclean => { FILES=>q[Makefile.old] }

# --- MakeMaker post_initialize section:


# --- MakeMaker const_config section:

# These definitions are from config.sh (via /usr/lib/perl/5.8/Config.pm).
# They may have been overridden via Makefile.PL or on the command line.
AR = ar
CC = cc
CCCDLFLAGS = -fPIC
CCDLFLAGS = -Wl,-E
DLEXT = so
DLSRC = dl_dlopen.xs
EXE_EXT = 
FULL_AR = /usr/bin/ar
LD = cc
LDDLFLAGS = -shared -L/usr/local/lib
LDFLAGS =  -L/usr/local/lib
LIBC = /lib/libc-2.6.1.so
LIB_EXT = .a
OBJ_EXT = .o
OSNAME = linux
OSVERS = 2.6.15.7
RANLIB = :
SITELIBEXP = /usr/local/share/perl/5.8.8
SITEARCHEXP = /usr/local/lib/perl/5.8.8
SO = so
VENDORARCHEXP = /usr/lib/perl5
VENDORLIBEXP = /usr/share/perl5


# --- MakeMaker constants section:
AR_STATIC_ARGS = cr
DIRFILESEP = /
DFSEP = $(DIRFILESEP)
NAME = SNMP::Info
NAME_SYM = SNMP_Info
VERSION = 2.00
VERSION_MACRO = VERSION
VERSION_SYM = 2_00
DEFINE_VERSION = -D$(VERSION_MACRO)=\"$(VERSION)\"
XS_VERSION = 2.00
XS_VERSION_MACRO = XS_VERSION
XS_DEFINE_VERSION = -D$(XS_VERSION_MACRO)=\"$(XS_VERSION)\"
INST_ARCHLIB = blib/arch
INST_SCRIPT = blib/script
INST_BIN = blib/bin
INST_LIB = blib/lib
INST_MAN1DIR = blib/man1
INST_MAN3DIR = blib/man3
MAN1EXT = 1p
MAN3EXT = 3pm
INSTALLDIRS = site
DESTDIR = 
PREFIX = $(SITEPREFIX)
PERLPREFIX = /usr
SITEPREFIX = /usr/local
VENDORPREFIX = /usr
INSTALLPRIVLIB = /usr/share/perl/5.8
DESTINSTALLPRIVLIB = $(DESTDIR)$(INSTALLPRIVLIB)
INSTALLSITELIB = /usr/local/share/perl/5.8.8
DESTINSTALLSITELIB = $(DESTDIR)$(INSTALLSITELIB)
INSTALLVENDORLIB = /usr/share/perl5
DESTINSTALLVENDORLIB = $(DESTDIR)$(INSTALLVENDORLIB)
INSTALLARCHLIB = /usr/lib/perl/5.8
DESTINSTALLARCHLIB = $(DESTDIR)$(INSTALLARCHLIB)
INSTALLSITEARCH = /usr/local/lib/perl/5.8.8
DESTINSTALLSITEARCH = $(DESTDIR)$(INSTALLSITEARCH)
INSTALLVENDORARCH = /usr/lib/perl5
DESTINSTALLVENDORARCH = $(DESTDIR)$(INSTALLVENDORARCH)
INSTALLBIN = /usr/bin
DESTINSTALLBIN = $(DESTDIR)$(INSTALLBIN)
INSTALLSITEBIN = /usr/local/bin
DESTINSTALLSITEBIN = $(DESTDIR)$(INSTALLSITEBIN)
INSTALLVENDORBIN = /usr/bin
DESTINSTALLVENDORBIN = $(DESTDIR)$(INSTALLVENDORBIN)
INSTALLSCRIPT = /usr/bin
DESTINSTALLSCRIPT = $(DESTDIR)$(INSTALLSCRIPT)
INSTALLSITESCRIPT = /usr/local/bin
DESTINSTALLSITESCRIPT = $(DESTDIR)$(INSTALLSITESCRIPT)
INSTALLVENDORSCRIPT = /usr/bin
DESTINSTALLVENDORSCRIPT = $(DESTDIR)$(INSTALLVENDORSCRIPT)
INSTALLMAN1DIR = /usr/share/man/man1
DESTINSTALLMAN1DIR = $(DESTDIR)$(INSTALLMAN1DIR)
INSTALLSITEMAN1DIR = /usr/local/man/man1
DESTINSTALLSITEMAN1DIR = $(DESTDIR)$(INSTALLSITEMAN1DIR)
INSTALLVENDORMAN1DIR = /usr/share/man/man1
DESTINSTALLVENDORMAN1DIR = $(DESTDIR)$(INSTALLVENDORMAN1DIR)
INSTALLMAN3DIR = /usr/share/man/man3
DESTINSTALLMAN3DIR = $(DESTDIR)$(INSTALLMAN3DIR)
INSTALLSITEMAN3DIR = /usr/local/man/man3
DESTINSTALLSITEMAN3DIR = $(DESTDIR)$(INSTALLSITEMAN3DIR)
INSTALLVENDORMAN3DIR = /usr/share/man/man3
DESTINSTALLVENDORMAN3DIR = $(DESTDIR)$(INSTALLVENDORMAN3DIR)
PERL_LIB = /usr/share/perl/5.8
PERL_ARCHLIB = /usr/lib/perl/5.8
LIBPERL_A = libperl.a
FIRST_MAKEFILE = Makefile
MAKEFILE_OLD = Makefile.old
MAKE_APERL_FILE = Makefile.aperl
PERLMAINCC = $(CC)
PERL_INC = /usr/lib/perl/5.8/CORE
PERL = /usr/bin/perl
FULLPERL = /usr/bin/perl
ABSPERL = $(PERL)
PERLRUN = $(PERL)
FULLPERLRUN = $(FULLPERL)
ABSPERLRUN = $(ABSPERL)
PERLRUNINST = $(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
FULLPERLRUNINST = $(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
ABSPERLRUNINST = $(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
PERL_CORE = 0
PERM_RW = 644
PERM_RWX = 755

MAKEMAKER   = /usr/local/share/perl/5.8.8/ExtUtils/MakeMaker.pm
MM_VERSION  = 6.44
MM_REVISION = 54639

# FULLEXT = Pathname for extension directory (eg Foo/Bar/Oracle).
# BASEEXT = Basename part of FULLEXT. May be just equal FULLEXT. (eg Oracle)
# PARENT_NAME = NAME without BASEEXT and no trailing :: (eg Foo::Bar)
# DLBASE  = Basename part of dynamic library. May be just equal BASEEXT.
MAKE = make
FULLEXT = SNMP/Info
BASEEXT = Info
PARENT_NAME = SNMP
DLBASE = $(BASEEXT)
VERSION_FROM = Info.pm
OBJECT = 
LDFROM = $(OBJECT)
LINKTYPE = dynamic
BOOTDEP = 

# Handy lists of source code files:
XS_FILES = 
C_FILES  = 
O_FILES  = 
H_FILES  = 
MAN1PODS = 
MAN3PODS = Info.pm \
	Info/Airespace.pm \
	Info/Bridge.pm \
	Info/CDP.pm \
	Info/CiscoConfig.pm \
	Info/CiscoImage.pm \
	Info/CiscoPortSecurity.pm \
	Info/CiscoPower.pm \
	Info/CiscoQOS.pm \
	Info/CiscoRTT.pm \
	Info/CiscoStack.pm \
	Info/CiscoStats.pm \
	Info/CiscoStpExtensions.pm \
	Info/CiscoVTP.pm \
	Info/Entity.pm \
	Info/EtherLike.pm \
	Info/FDP.pm \
	Info/IEEE802dot11.pm \
	Info/LLDP.pm \
	Info/Layer1.pm \
	Info/Layer1/Allied.pm \
	Info/Layer1/Asante.pm \
	Info/Layer1/Bayhub.pm \
	Info/Layer1/Cyclades.pm \
	Info/Layer1/S3000.pm \
	Info/Layer2.pm \
	Info/Layer2/Airespace.pm \
	Info/Layer2/Aironet.pm \
	Info/Layer2/Allied.pm \
	Info/Layer2/Aruba.pm \
	Info/Layer2/Bay.pm \
	Info/Layer2/Baystack.pm \
	Info/Layer2/C1900.pm \
	Info/Layer2/C2900.pm \
	Info/Layer2/Catalyst.pm \
	Info/Layer2/Centillion.pm \
	Info/Layer2/Cisco.pm \
	Info/Layer2/Foundry.pm \
	Info/Layer2/HP.pm \
	Info/Layer2/N2270.pm \
	Info/Layer2/NAP222x.pm \
	Info/Layer2/Netgear.pm \
	Info/Layer2/Orinoco.pm \
	Info/Layer2/ZyXEL_DSLAM.pm \
	Info/Layer3.pm \
	Info/Layer3/Aironet.pm \
	Info/Layer3/AlcatelLucent.pm \
	Info/Layer3/AlteonAD.pm \
	Info/Layer3/BayRS.pm \
	Info/Layer3/C3550.pm \
	Info/Layer3/C4000.pm \
	Info/Layer3/C6500.pm \
	Info/Layer3/Cisco.pm \
	Info/Layer3/Contivity.pm \
	Info/Layer3/Dell.pm \
	Info/Layer3/Enterasys.pm \
	Info/Layer3/Extreme.pm \
	Info/Layer3/Foundry.pm \
	Info/Layer3/HP9300.pm \
	Info/Layer3/Juniper.pm \
	Info/Layer3/Microsoft.pm \
	Info/Layer3/N1600.pm \
	Info/Layer3/NetSNMP.pm \
	Info/Layer3/Netscreen.pm \
	Info/Layer3/Passport.pm \
	Info/Layer3/Sun.pm \
	Info/Layer3/Timetra.pm \
	Info/MAU.pm \
	Info/NortelStack.pm \
	Info/PowerEthernet.pm \
	Info/RapidCity.pm \
	Info/SONMP.pm

# Where is the Config information that we are using/depend on
CONFIGDEP = $(PERL_ARCHLIB)$(DFSEP)Config.pm $(PERL_INC)$(DFSEP)config.h

# Where to build things
INST_LIBDIR      = $(INST_LIB)/SNMP
INST_ARCHLIBDIR  = $(INST_ARCHLIB)/SNMP

INST_AUTODIR     = $(INST_LIB)/auto/$(FULLEXT)
INST_ARCHAUTODIR = $(INST_ARCHLIB)/auto/$(FULLEXT)

INST_STATIC      = 
INST_DYNAMIC     = 
INST_BOOT        = 

# Extra linker info
EXPORT_LIST        = 
PERL_ARCHIVE       = 
PERL_ARCHIVE_AFTER = 


TO_INST_PM = Info.pm \
	Info/Airespace.pm \
	Info/Bridge.pm \
	Info/CDP.pm \
	Info/CiscoConfig.pm \
	Info/CiscoImage.pm \
	Info/CiscoPortSecurity.pm \
	Info/CiscoPower.pm \
	Info/CiscoQOS.pm \
	Info/CiscoRTT.pm \
	Info/CiscoStack.pm \
	Info/CiscoStats.pm \
	Info/CiscoStpExtensions.pm \
	Info/CiscoVTP.pm \
	Info/Entity.pm \
	Info/EtherLike.pm \
	Info/FDP.pm \
	Info/IEEE802dot11.pm \
	Info/LLDP.pm \
	Info/Layer1.pm \
	Info/Layer1/Allied.pm \
	Info/Layer1/Asante.pm \
	Info/Layer1/Bayhub.pm \
	Info/Layer1/Cyclades.pm \
	Info/Layer1/S3000.pm \
	Info/Layer2.pm \
	Info/Layer2/Airespace.pm \
	Info/Layer2/Aironet.pm \
	Info/Layer2/Allied.pm \
	Info/Layer2/Aruba.pm \
	Info/Layer2/Bay.pm \
	Info/Layer2/Baystack.pm \
	Info/Layer2/C1900.pm \
	Info/Layer2/C2900.pm \
	Info/Layer2/Catalyst.pm \
	Info/Layer2/Centillion.pm \
	Info/Layer2/Cisco.pm \
	Info/Layer2/Foundry.pm \
	Info/Layer2/HP.pm \
	Info/Layer2/N2270.pm \
	Info/Layer2/NAP222x.pm \
	Info/Layer2/Netgear.pm \
	Info/Layer2/Orinoco.pm \
	Info/Layer2/ZyXEL_DSLAM.pm \
	Info/Layer3.pm \
	Info/Layer3/Aironet.pm \
	Info/Layer3/AlcatelLucent.pm \
	Info/Layer3/AlteonAD.pm \
	Info/Layer3/BayRS.pm \
	Info/Layer3/C3550.pm \
	Info/Layer3/C4000.pm \
	Info/Layer3/C6500.pm \
	Info/Layer3/Cisco.pm \
	Info/Layer3/Contivity.pm \
	Info/Layer3/Dell.pm \
	Info/Layer3/Enterasys.pm \
	Info/Layer3/Extreme.pm \
	Info/Layer3/Foundry.pm \
	Info/Layer3/HP9300.pm \
	Info/Layer3/Juniper.pm \
	Info/Layer3/Microsoft.pm \
	Info/Layer3/N1600.pm \
	Info/Layer3/NetSNMP.pm \
	Info/Layer3/Netscreen.pm \
	Info/Layer3/Passport.pm \
	Info/Layer3/Sun.pm \
	Info/Layer3/Timetra.pm \
	Info/MAU.pm \
	Info/NortelStack.pm \
	Info/PowerEthernet.pm \
	Info/RapidCity.pm \
	Info/SONMP.pm

PM_TO_BLIB = Info/Layer3/NetSNMP.pm \
	$(INST_LIB)/SNMP/Info/Layer3/NetSNMP.pm \
	Info/Layer2/HP.pm \
	$(INST_LIB)/SNMP/Info/Layer2/HP.pm \
	Info/Layer2/C2900.pm \
	$(INST_LIB)/SNMP/Info/Layer2/C2900.pm \
	Info/Layer2/Aruba.pm \
	$(INST_LIB)/SNMP/Info/Layer2/Aruba.pm \
	Info/CiscoQOS.pm \
	$(INST_LIB)/SNMP/Info/CiscoQOS.pm \
	Info/Layer3/Netscreen.pm \
	$(INST_LIB)/SNMP/Info/Layer3/Netscreen.pm \
	Info/Layer3/Sun.pm \
	$(INST_LIB)/SNMP/Info/Layer3/Sun.pm \
	Info/Layer3.pm \
	$(INST_LIB)/SNMP/Info/Layer3.pm \
	Info/Layer2/Baystack.pm \
	$(INST_LIB)/SNMP/Info/Layer2/Baystack.pm \
	Info.pm \
	$(INST_LIB)/SNMP/Info.pm \
	Info/Layer3/C4000.pm \
	$(INST_LIB)/SNMP/Info/Layer3/C4000.pm \
	Info/Layer2/Netgear.pm \
	$(INST_LIB)/SNMP/Info/Layer2/Netgear.pm \
	Info/Layer3/Cisco.pm \
	$(INST_LIB)/SNMP/Info/Layer3/Cisco.pm \
	Info/CiscoConfig.pm \
	$(INST_LIB)/SNMP/Info/CiscoConfig.pm \
	Info/Entity.pm \
	$(INST_LIB)/SNMP/Info/Entity.pm \
	Info/SONMP.pm \
	$(INST_LIB)/SNMP/Info/SONMP.pm \
	Info/Layer1/S3000.pm \
	$(INST_LIB)/SNMP/Info/Layer1/S3000.pm \
	Info/Layer3/Microsoft.pm \
	$(INST_LIB)/SNMP/Info/Layer3/Microsoft.pm \
	Info/RapidCity.pm \
	$(INST_LIB)/SNMP/Info/RapidCity.pm \
	Info/Layer3/HP9300.pm \
	$(INST_LIB)/SNMP/Info/Layer3/HP9300.pm \
	Info/Layer3/C3550.pm \
	$(INST_LIB)/SNMP/Info/Layer3/C3550.pm \
	Info/Layer2/ZyXEL_DSLAM.pm \
	$(INST_LIB)/SNMP/Info/Layer2/ZyXEL_DSLAM.pm \
	Info/Layer2/N2270.pm \
	$(INST_LIB)/SNMP/Info/Layer2/N2270.pm \
	Info/CiscoStpExtensions.pm \
	$(INST_LIB)/SNMP/Info/CiscoStpExtensions.pm \
	Info/Layer2/Allied.pm \
	$(INST_LIB)/SNMP/Info/Layer2/Allied.pm \
	Info/Layer2/Bay.pm \
	$(INST_LIB)/SNMP/Info/Layer2/Bay.pm \
	Info/Layer2.pm \
	$(INST_LIB)/SNMP/Info/Layer2.pm \
	Info/Layer3/Passport.pm \
	$(INST_LIB)/SNMP/Info/Layer3/Passport.pm \
	Info/Layer2/Catalyst.pm \
	$(INST_LIB)/SNMP/Info/Layer2/Catalyst.pm \
	Info/Layer3/Extreme.pm \
	$(INST_LIB)/SNMP/Info/Layer3/Extreme.pm \
	Info/CiscoVTP.pm \
	$(INST_LIB)/SNMP/Info/CiscoVTP.pm \
	Info/IEEE802dot11.pm \
	$(INST_LIB)/SNMP/Info/IEEE802dot11.pm \
	Info/Layer2/Airespace.pm \
	$(INST_LIB)/SNMP/Info/Layer2/Airespace.pm \
	Info/FDP.pm \
	$(INST_LIB)/SNMP/Info/FDP.pm \
	Info/Layer2/Orinoco.pm \
	$(INST_LIB)/SNMP/Info/Layer2/Orinoco.pm \
	Info/Layer3/Contivity.pm \
	$(INST_LIB)/SNMP/Info/Layer3/Contivity.pm \
	Info/Layer3/AlcatelLucent.pm \
	$(INST_LIB)/SNMP/Info/Layer3/AlcatelLucent.pm \
	Info/Layer3/BayRS.pm \
	$(INST_LIB)/SNMP/Info/Layer3/BayRS.pm \
	Info/Layer3/C6500.pm \
	$(INST_LIB)/SNMP/Info/Layer3/C6500.pm \
	Info/CiscoRTT.pm \
	$(INST_LIB)/SNMP/Info/CiscoRTT.pm \
	Info/CiscoPower.pm \
	$(INST_LIB)/SNMP/Info/CiscoPower.pm \
	Info/NortelStack.pm \
	$(INST_LIB)/SNMP/Info/NortelStack.pm \
	Info/LLDP.pm \
	$(INST_LIB)/SNMP/Info/LLDP.pm \
	Info/CiscoStats.pm \
	$(INST_LIB)/SNMP/Info/CiscoStats.pm \
	Info/Layer1.pm \
	$(INST_LIB)/SNMP/Info/Layer1.pm \
	Info/Layer1/Allied.pm \
	$(INST_LIB)/SNMP/Info/Layer1/Allied.pm \
	Info/CDP.pm \
	$(INST_LIB)/SNMP/Info/CDP.pm \
	Info/MAU.pm \
	$(INST_LIB)/SNMP/Info/MAU.pm \
	Info/Layer1/Asante.pm \
	$(INST_LIB)/SNMP/Info/Layer1/Asante.pm \
	Info/Layer2/C1900.pm \
	$(INST_LIB)/SNMP/Info/Layer2/C1900.pm \
	Info/Bridge.pm \
	$(INST_LIB)/SNMP/Info/Bridge.pm \
	Info/Layer3/N1600.pm \
	$(INST_LIB)/SNMP/Info/Layer3/N1600.pm \
	Info/EtherLike.pm \
	$(INST_LIB)/SNMP/Info/EtherLike.pm \
	Info/Layer1/Cyclades.pm \
	$(INST_LIB)/SNMP/Info/Layer1/Cyclades.pm \
	Info/Layer2/NAP222x.pm \
	$(INST_LIB)/SNMP/Info/Layer2/NAP222x.pm \
	Info/Layer2/Foundry.pm \
	$(INST_LIB)/SNMP/Info/Layer2/Foundry.pm \
	Info/PowerEthernet.pm \
	$(INST_LIB)/SNMP/Info/PowerEthernet.pm \
	Info/CiscoStack.pm \
	$(INST_LIB)/SNMP/Info/CiscoStack.pm \
	Info/Layer2/Centillion.pm \
	$(INST_LIB)/SNMP/Info/Layer2/Centillion.pm \
	Info/Layer3/Enterasys.pm \
	$(INST_LIB)/SNMP/Info/Layer3/Enterasys.pm \
	Info/Layer3/Dell.pm \
	$(INST_LIB)/SNMP/Info/Layer3/Dell.pm \
	Info/Airespace.pm \
	$(INST_LIB)/SNMP/Info/Airespace.pm \
	Info/CiscoImage.pm \
	$(INST_LIB)/SNMP/Info/CiscoImage.pm \
	Info/CiscoPortSecurity.pm \
	$(INST_LIB)/SNMP/Info/CiscoPortSecurity.pm \
	Info/Layer3/Juniper.pm \
	$(INST_LIB)/SNMP/Info/Layer3/Juniper.pm \
	Info/Layer3/Timetra.pm \
	$(INST_LIB)/SNMP/Info/Layer3/Timetra.pm \
	Info/Layer3/Foundry.pm \
	$(INST_LIB)/SNMP/Info/Layer3/Foundry.pm \
	Info/Layer2/Cisco.pm \
	$(INST_LIB)/SNMP/Info/Layer2/Cisco.pm \
	Info/Layer3/AlteonAD.pm \
	$(INST_LIB)/SNMP/Info/Layer3/AlteonAD.pm \
	Info/Layer3/Aironet.pm \
	$(INST_LIB)/SNMP/Info/Layer3/Aironet.pm \
	Info/Layer1/Bayhub.pm \
	$(INST_LIB)/SNMP/Info/Layer1/Bayhub.pm \
	Info/Layer2/Aironet.pm \
	$(INST_LIB)/SNMP/Info/Layer2/Aironet.pm


# --- MakeMaker platform_constants section:
MM_Unix_VERSION = 6.44
PERL_MALLOC_DEF = -DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc


# --- MakeMaker tool_autosplit section:
# Usage: $(AUTOSPLITFILE) FileToSplit AutoDirToSplitInto
AUTOSPLITFILE = $(ABSPERLRUN)  -e 'use AutoSplit;  autosplit($$ARGV[0], $$ARGV[1], 0, 1, 1)' --



# --- MakeMaker tool_xsubpp section:


# --- MakeMaker tools_other section:
SHELL = /bin/sh
CHMOD = chmod
CP = cp
MV = mv
NOOP = $(SHELL) -c true
NOECHO = @
RM_F = rm -f
RM_RF = rm -rf
TEST_F = test -f
TOUCH = touch
UMASK_NULL = umask 0
DEV_NULL = > /dev/null 2>&1
MKPATH = $(ABSPERLRUN) "-MExtUtils::Command" -e mkpath
EQUALIZE_TIMESTAMP = $(ABSPERLRUN) "-MExtUtils::Command" -e eqtime
ECHO = echo
ECHO_N = echo -n
UNINST = 0
VERBINST = 0
MOD_INSTALL = $(ABSPERLRUN) -MExtUtils::Install -e 'install({@ARGV}, '\''$(VERBINST)'\'', 0, '\''$(UNINST)'\'');' --
DOC_INSTALL = $(ABSPERLRUN) "-MExtUtils::Command::MM" -e perllocal_install
UNINSTALL = $(ABSPERLRUN) "-MExtUtils::Command::MM" -e uninstall
WARN_IF_OLD_PACKLIST = $(ABSPERLRUN) "-MExtUtils::Command::MM" -e warn_if_old_packlist
MACROSTART = 
MACROEND = 
USEMAKEFILE = -f
FIXIN = $(PERLRUN) "-MExtUtils::MY" -e "MY->fixin(shift)"


# --- MakeMaker makemakerdflt section:
makemakerdflt : all
	$(NOECHO) $(NOOP)


# --- MakeMaker dist section:
TAR = tar
TARFLAGS = cvf
ZIP = zip
ZIPFLAGS = -r
COMPRESS = gzip -9f
SUFFIX = gz
SHAR = shar
PREOP = $(NOECHO) $(NOOP)
POSTOP = $(NOECHO) $(NOOP)
TO_UNIX = $(NOECHO) $(NOOP)
CI = ci -u
RCS_LABEL = rcs -Nv$(VERSION_SYM): -q
DIST_CP = best
DIST_DEFAULT = tardist
DISTNAME = SNMP-Info
DISTVNAME = SNMP-Info-2.00


# --- MakeMaker macro section:


# --- MakeMaker depend section:


# --- MakeMaker cflags section:


# --- MakeMaker const_loadlibs section:


# --- MakeMaker const_cccmd section:


# --- MakeMaker post_constants section:


# --- MakeMaker pasthru section:

PASTHRU = LIBPERL_A="$(LIBPERL_A)"\
	LINKTYPE="$(LINKTYPE)"\
	PREFIX="$(PREFIX)"


# --- MakeMaker special_targets section:
.SUFFIXES : .xs .c .C .cpp .i .s .cxx .cc $(OBJ_EXT)

.PHONY: all config static dynamic test linkext manifest blibdirs clean realclean disttest distdir



# --- MakeMaker c_o section:


# --- MakeMaker xs_c section:


# --- MakeMaker xs_o section:


# --- MakeMaker top_targets section:
all :: pure_all manifypods
	$(NOECHO) $(NOOP)


pure_all :: config pm_to_blib subdirs linkext
	$(NOECHO) $(NOOP)

subdirs :: $(MYEXTLIB)
	$(NOECHO) $(NOOP)

config :: $(FIRST_MAKEFILE) blibdirs
	$(NOECHO) $(NOOP)

help :
	perldoc ExtUtils::MakeMaker


# --- MakeMaker blibdirs section:
blibdirs : $(INST_LIBDIR)$(DFSEP).exists $(INST_ARCHLIB)$(DFSEP).exists $(INST_AUTODIR)$(DFSEP).exists $(INST_ARCHAUTODIR)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists $(INST_SCRIPT)$(DFSEP).exists $(INST_MAN1DIR)$(DFSEP).exists $(INST_MAN3DIR)$(DFSEP).exists
	$(NOECHO) $(NOOP)

# Backwards compat with 6.18 through 6.25
blibdirs.ts : blibdirs
	$(NOECHO) $(NOOP)

$(INST_LIBDIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_LIBDIR)
	$(NOECHO) $(CHMOD) 755 $(INST_LIBDIR)
	$(NOECHO) $(TOUCH) $(INST_LIBDIR)$(DFSEP).exists

$(INST_ARCHLIB)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHLIB)
	$(NOECHO) $(CHMOD) 755 $(INST_ARCHLIB)
	$(NOECHO) $(TOUCH) $(INST_ARCHLIB)$(DFSEP).exists

$(INST_AUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_AUTODIR)
	$(NOECHO) $(CHMOD) 755 $(INST_AUTODIR)
	$(NOECHO) $(TOUCH) $(INST_AUTODIR)$(DFSEP).exists

$(INST_ARCHAUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHAUTODIR)
	$(NOECHO) $(CHMOD) 755 $(INST_ARCHAUTODIR)
	$(NOECHO) $(TOUCH) $(INST_ARCHAUTODIR)$(DFSEP).exists

$(INST_BIN)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_BIN)
	$(NOECHO) $(CHMOD) 755 $(INST_BIN)
	$(NOECHO) $(TOUCH) $(INST_BIN)$(DFSEP).exists

$(INST_SCRIPT)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_SCRIPT)
	$(NOECHO) $(CHMOD) 755 $(INST_SCRIPT)
	$(NOECHO) $(TOUCH) $(INST_SCRIPT)$(DFSEP).exists

$(INST_MAN1DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN1DIR)
	$(NOECHO) $(CHMOD) 755 $(INST_MAN1DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN1DIR)$(DFSEP).exists

$(INST_MAN3DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN3DIR)
	$(NOECHO) $(CHMOD) 755 $(INST_MAN3DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN3DIR)$(DFSEP).exists



# --- MakeMaker linkext section:

linkext :: $(LINKTYPE)
	$(NOECHO) $(NOOP)


# --- MakeMaker dlsyms section:


# --- MakeMaker dynamic section:

dynamic :: $(FIRST_MAKEFILE) $(INST_DYNAMIC) $(INST_BOOT)
	$(NOECHO) $(NOOP)


# --- MakeMaker dynamic_bs section:

BOOTSTRAP =


# --- MakeMaker dynamic_lib section:


# --- MakeMaker static section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make static"
static :: $(FIRST_MAKEFILE) $(INST_STATIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker static_lib section:


# --- MakeMaker manifypods section:

POD2MAN_EXE = $(PERLRUN) "-MExtUtils::Command::MM" -e pod2man "--"
POD2MAN = $(POD2MAN_EXE)


manifypods : pure_all  \
	Info/Layer3/NetSNMP.pm \
	Info/Layer2/HP.pm \
	Info/Layer2/C2900.pm \
	Info/Layer2/Aruba.pm \
	Info/CiscoQOS.pm \
	Info/Layer3/Netscreen.pm \
	Info/Layer3/Sun.pm \
	Info/Layer3.pm \
	Info/Layer2/Baystack.pm \
	Info.pm \
	Info/Layer3/C4000.pm \
	Info/Layer2/Netgear.pm \
	Info/Layer3/Cisco.pm \
	Info/CiscoConfig.pm \
	Info/Entity.pm \
	Info/SONMP.pm \
	Info/Layer1/S3000.pm \
	Info/Layer3/Microsoft.pm \
	Info/RapidCity.pm \
	Info/Layer3/HP9300.pm \
	Info/Layer3/C3550.pm \
	Info/Layer2/ZyXEL_DSLAM.pm \
	Info/Layer2/N2270.pm \
	Info/CiscoStpExtensions.pm \
	Info/Layer2/Allied.pm \
	Info/Layer2/Bay.pm \
	Info/Layer2.pm \
	Info/Layer3/Passport.pm \
	Info/Layer2/Catalyst.pm \
	Info/Layer3/Extreme.pm \
	Info/CiscoVTP.pm \
	Info/IEEE802dot11.pm \
	Info/Layer2/Airespace.pm \
	Info/FDP.pm \
	Info/Layer2/Orinoco.pm \
	Info/Layer3/Contivity.pm \
	Info/Layer3/AlcatelLucent.pm \
	Info/Layer3/BayRS.pm \
	Info/Layer3/C6500.pm \
	Info/CiscoRTT.pm \
	Info/CiscoPower.pm \
	Info/NortelStack.pm \
	Info/LLDP.pm \
	Info/CiscoStats.pm \
	Info/Layer1.pm \
	Info/Layer1/Allied.pm \
	Info/CDP.pm \
	Info/MAU.pm \
	Info/Layer1/Asante.pm \
	Info/Layer2/C1900.pm \
	Info/Bridge.pm \
	Info/Layer3/N1600.pm \
	Info/EtherLike.pm \
	Info/Layer1/Cyclades.pm \
	Info/Layer2/NAP222x.pm \
	Info/Layer2/Foundry.pm \
	Info/PowerEthernet.pm \
	Info/CiscoStack.pm \
	Info/Layer2/Centillion.pm \
	Info/Layer3/Enterasys.pm \
	Info/Layer3/Dell.pm \
	Info/Airespace.pm \
	Info/CiscoImage.pm \
	Info/CiscoPortSecurity.pm \
	Info/Layer3/Juniper.pm \
	Info/Layer3/Timetra.pm \
	Info/Layer3/Foundry.pm \
	Info/Layer2/Cisco.pm \
	Info/Layer3/AlteonAD.pm \
	Info/Layer3/Aironet.pm \
	Info/Layer1/Bayhub.pm \
	Info/Layer2/Aironet.pm
	$(NOECHO) $(POD2MAN) --section=3 --perm_rw=$(PERM_RW) \
	  Info/Layer3/NetSNMP.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::NetSNMP.$(MAN3EXT) \
	  Info/Layer2/HP.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::HP.$(MAN3EXT) \
	  Info/Layer2/C2900.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::C2900.$(MAN3EXT) \
	  Info/Layer2/Aruba.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::Aruba.$(MAN3EXT) \
	  Info/CiscoQOS.pm $(INST_MAN3DIR)/SNMP::Info::CiscoQOS.$(MAN3EXT) \
	  Info/Layer3/Netscreen.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::Netscreen.$(MAN3EXT) \
	  Info/Layer3/Sun.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::Sun.$(MAN3EXT) \
	  Info/Layer3.pm $(INST_MAN3DIR)/SNMP::Info::Layer3.$(MAN3EXT) \
	  Info/Layer2/Baystack.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::Baystack.$(MAN3EXT) \
	  Info.pm $(INST_MAN3DIR)/SNMP::Info.$(MAN3EXT) \
	  Info/Layer3/C4000.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::C4000.$(MAN3EXT) \
	  Info/Layer2/Netgear.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::Netgear.$(MAN3EXT) \
	  Info/Layer3/Cisco.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::Cisco.$(MAN3EXT) \
	  Info/CiscoConfig.pm $(INST_MAN3DIR)/SNMP::Info::CiscoConfig.$(MAN3EXT) \
	  Info/Entity.pm $(INST_MAN3DIR)/SNMP::Info::Entity.$(MAN3EXT) \
	  Info/SONMP.pm $(INST_MAN3DIR)/SNMP::Info::SONMP.$(MAN3EXT) \
	  Info/Layer1/S3000.pm $(INST_MAN3DIR)/SNMP::Info::Layer1::S3000.$(MAN3EXT) \
	  Info/Layer3/Microsoft.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::Microsoft.$(MAN3EXT) \
	  Info/RapidCity.pm $(INST_MAN3DIR)/SNMP::Info::RapidCity.$(MAN3EXT) \
	  Info/Layer3/HP9300.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::HP9300.$(MAN3EXT) \
	  Info/Layer3/C3550.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::C3550.$(MAN3EXT) \
	  Info/Layer2/ZyXEL_DSLAM.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::ZyXEL_DSLAM.$(MAN3EXT) \
	  Info/Layer2/N2270.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::N2270.$(MAN3EXT) \
	  Info/CiscoStpExtensions.pm $(INST_MAN3DIR)/SNMP::Info::CiscoStpExtensions.$(MAN3EXT) \
	  Info/Layer2/Allied.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::Allied.$(MAN3EXT) \
	  Info/Layer2/Bay.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::Bay.$(MAN3EXT) \
	  Info/Layer2.pm $(INST_MAN3DIR)/SNMP::Info::Layer2.$(MAN3EXT) \
	  Info/Layer3/Passport.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::Passport.$(MAN3EXT) \
	  Info/Layer2/Catalyst.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::Catalyst.$(MAN3EXT) \
	  Info/Layer3/Extreme.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::Extreme.$(MAN3EXT) \
	  Info/CiscoVTP.pm $(INST_MAN3DIR)/SNMP::Info::CiscoVTP.$(MAN3EXT) \
	  Info/IEEE802dot11.pm $(INST_MAN3DIR)/SNMP::Info::IEEE802dot11.$(MAN3EXT) \
	  Info/Layer2/Airespace.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::Airespace.$(MAN3EXT) \
	  Info/FDP.pm $(INST_MAN3DIR)/SNMP::Info::FDP.$(MAN3EXT) \
	  Info/Layer2/Orinoco.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::Orinoco.$(MAN3EXT) \
	  Info/Layer3/Contivity.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::Contivity.$(MAN3EXT) \
	  Info/Layer3/AlcatelLucent.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::AlcatelLucent.$(MAN3EXT) \
	  Info/Layer3/BayRS.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::BayRS.$(MAN3EXT) \
	  Info/Layer3/C6500.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::C6500.$(MAN3EXT) \
	  Info/CiscoRTT.pm $(INST_MAN3DIR)/SNMP::Info::CiscoRTT.$(MAN3EXT) \
	  Info/CiscoPower.pm $(INST_MAN3DIR)/SNMP::Info::CiscoPower.$(MAN3EXT) \
	  Info/NortelStack.pm $(INST_MAN3DIR)/SNMP::Info::NortelStack.$(MAN3EXT) \
	  Info/LLDP.pm $(INST_MAN3DIR)/SNMP::Info::LLDP.$(MAN3EXT) \
	  Info/CiscoStats.pm $(INST_MAN3DIR)/SNMP::Info::CiscoStats.$(MAN3EXT) \
	  Info/Layer1.pm $(INST_MAN3DIR)/SNMP::Info::Layer1.$(MAN3EXT) \
	  Info/Layer1/Allied.pm $(INST_MAN3DIR)/SNMP::Info::Layer1::Allied.$(MAN3EXT) \
	  Info/CDP.pm $(INST_MAN3DIR)/SNMP::Info::CDP.$(MAN3EXT) \
	  Info/MAU.pm $(INST_MAN3DIR)/SNMP::Info::MAU.$(MAN3EXT) \
	  Info/Layer1/Asante.pm $(INST_MAN3DIR)/SNMP::Info::Layer1::Asante.$(MAN3EXT) \
	  Info/Layer2/C1900.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::C1900.$(MAN3EXT) \
	  Info/Bridge.pm $(INST_MAN3DIR)/SNMP::Info::Bridge.$(MAN3EXT) \
	  Info/Layer3/N1600.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::N1600.$(MAN3EXT) \
	  Info/EtherLike.pm $(INST_MAN3DIR)/SNMP::Info::EtherLike.$(MAN3EXT) \
	  Info/Layer1/Cyclades.pm $(INST_MAN3DIR)/SNMP::Info::Layer1::Cyclades.$(MAN3EXT) \
	  Info/Layer2/NAP222x.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::NAP222x.$(MAN3EXT) \
	  Info/Layer2/Foundry.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::Foundry.$(MAN3EXT) \
	  Info/PowerEthernet.pm $(INST_MAN3DIR)/SNMP::Info::PowerEthernet.$(MAN3EXT) \
	  Info/CiscoStack.pm $(INST_MAN3DIR)/SNMP::Info::CiscoStack.$(MAN3EXT) \
	  Info/Layer2/Centillion.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::Centillion.$(MAN3EXT) \
	  Info/Layer3/Enterasys.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::Enterasys.$(MAN3EXT) \
	  Info/Layer3/Dell.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::Dell.$(MAN3EXT) \
	  Info/Airespace.pm $(INST_MAN3DIR)/SNMP::Info::Airespace.$(MAN3EXT) \
	  Info/CiscoImage.pm $(INST_MAN3DIR)/SNMP::Info::CiscoImage.$(MAN3EXT) \
	  Info/CiscoPortSecurity.pm $(INST_MAN3DIR)/SNMP::Info::CiscoPortSecurity.$(MAN3EXT) \
	  Info/Layer3/Juniper.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::Juniper.$(MAN3EXT) \
	  Info/Layer3/Timetra.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::Timetra.$(MAN3EXT) \
	  Info/Layer3/Foundry.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::Foundry.$(MAN3EXT) \
	  Info/Layer2/Cisco.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::Cisco.$(MAN3EXT) \
	  Info/Layer3/AlteonAD.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::AlteonAD.$(MAN3EXT) \
	  Info/Layer3/Aironet.pm $(INST_MAN3DIR)/SNMP::Info::Layer3::Aironet.$(MAN3EXT) \
	  Info/Layer1/Bayhub.pm $(INST_MAN3DIR)/SNMP::Info::Layer1::Bayhub.$(MAN3EXT) \
	  Info/Layer2/Aironet.pm $(INST_MAN3DIR)/SNMP::Info::Layer2::Aironet.$(MAN3EXT) 




# --- MakeMaker processPL section:


# --- MakeMaker installbin section:


# --- MakeMaker subdirs section:

# none

# --- MakeMaker clean_subdirs section:
clean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker clean section:

# Delete temporary files but do not touch installed files. We don't delete
# the Makefile here so a later make realclean still has a makefile to use.

clean :: clean_subdirs
	- $(RM_F) \
	  *$(LIB_EXT) core \
	  core.[0-9] $(INST_ARCHAUTODIR)/extralibs.all \
	  core.[0-9][0-9] $(BASEEXT).bso \
	  pm_to_blib.ts core.[0-9][0-9][0-9][0-9] \
	  $(BASEEXT).x $(BOOTSTRAP) \
	  perl$(EXE_EXT) tmon.out \
	  *$(OBJ_EXT) pm_to_blib \
	  $(INST_ARCHAUTODIR)/extralibs.ld blibdirs.ts \
	  core.[0-9][0-9][0-9][0-9][0-9] *perl.core \
	  core.*perl.*.? $(MAKE_APERL_FILE) \
	  perl $(BASEEXT).def \
	  core.[0-9][0-9][0-9] mon.out \
	  lib$(BASEEXT).def perlmain.c \
	  perl.exe so_locations \
	  $(BASEEXT).exp 
	- $(RM_RF) \
	  SNMP-Info-* blib 
	- $(MV) $(FIRST_MAKEFILE) $(MAKEFILE_OLD) $(DEV_NULL)


# --- MakeMaker realclean_subdirs section:
realclean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker realclean section:
# Delete temporary files (via clean) and also delete dist files
realclean purge ::  clean realclean_subdirs
	- $(RM_F) \
	  $(MAKEFILE_OLD) $(FIRST_MAKEFILE) 
	- $(RM_RF) \
	  Makefile.old $(DISTVNAME) 


# --- MakeMaker metafile section:
metafile : create_distdir
	$(NOECHO) $(ECHO) Generating META.yml
	$(NOECHO) $(ECHO) '--- #YAML:1.0' > META_new.yml
	$(NOECHO) $(ECHO) 'name:                SNMP-Info' >> META_new.yml
	$(NOECHO) $(ECHO) 'version:             2.00' >> META_new.yml
	$(NOECHO) $(ECHO) 'abstract:            Object Oriented Perl5 Interface to Network devices and MIBs through SNMP. ' >> META_new.yml
	$(NOECHO) $(ECHO) 'license:             bsd' >> META_new.yml
	$(NOECHO) $(ECHO) 'author:              ' >> META_new.yml
	$(NOECHO) $(ECHO) '    - Eric A. Miller <emiller@cpan.org>' >> META_new.yml
	$(NOECHO) $(ECHO) 'generated_by:        ExtUtils::MakeMaker version 6.44' >> META_new.yml
	$(NOECHO) $(ECHO) 'distribution_type:   module' >> META_new.yml
	$(NOECHO) $(ECHO) 'requires:     ' >> META_new.yml
	$(NOECHO) $(ECHO) '    Math::BigInt:                  0' >> META_new.yml
	$(NOECHO) $(ECHO) '    SNMP:                          0' >> META_new.yml
	$(NOECHO) $(ECHO) '    Test::More:                    0' >> META_new.yml
	$(NOECHO) $(ECHO) 'meta-spec:' >> META_new.yml
	$(NOECHO) $(ECHO) '    url:     http://module-build.sourceforge.net/META-spec-v1.3.html' >> META_new.yml
	$(NOECHO) $(ECHO) '    version: 1.3' >> META_new.yml
	-$(NOECHO) $(MV) META_new.yml $(DISTVNAME)/META.yml


# --- MakeMaker signature section:
signature :
	cpansign -s


# --- MakeMaker dist_basics section:
distclean :: realclean distcheck
	$(NOECHO) $(NOOP)

distcheck :
	$(PERLRUN) "-MExtUtils::Manifest=fullcheck" -e fullcheck

skipcheck :
	$(PERLRUN) "-MExtUtils::Manifest=skipcheck" -e skipcheck

manifest :
	$(PERLRUN) "-MExtUtils::Manifest=mkmanifest" -e mkmanifest

veryclean : realclean
	$(RM_F) *~ */*~ *.orig */*.orig *.bak */*.bak *.old */*.old 



# --- MakeMaker dist_core section:

dist : $(DIST_DEFAULT) $(FIRST_MAKEFILE)
	$(NOECHO) $(ABSPERLRUN) -l -e 'print '\''Warning: Makefile possibly out of date with $(VERSION_FROM)'\''' \
	  -e '    if -e '\''$(VERSION_FROM)'\'' and -M '\''$(VERSION_FROM)'\'' < -M '\''$(FIRST_MAKEFILE)'\'';' --

tardist : $(DISTVNAME).tar$(SUFFIX)
	$(NOECHO) $(NOOP)

uutardist : $(DISTVNAME).tar$(SUFFIX)
	uuencode $(DISTVNAME).tar$(SUFFIX) $(DISTVNAME).tar$(SUFFIX) > $(DISTVNAME).tar$(SUFFIX)_uu

$(DISTVNAME).tar$(SUFFIX) : distdir
	$(PREOP)
	$(TO_UNIX)
	$(TAR) $(TARFLAGS) $(DISTVNAME).tar $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(COMPRESS) $(DISTVNAME).tar
	$(POSTOP)

zipdist : $(DISTVNAME).zip
	$(NOECHO) $(NOOP)

$(DISTVNAME).zip : distdir
	$(PREOP)
	$(ZIP) $(ZIPFLAGS) $(DISTVNAME).zip $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)

shdist : distdir
	$(PREOP)
	$(SHAR) $(DISTVNAME) > $(DISTVNAME).shar
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)


# --- MakeMaker distdir section:
create_distdir :
	$(RM_RF) $(DISTVNAME)
	$(PERLRUN) "-MExtUtils::Manifest=manicopy,maniread" \
		-e "manicopy(maniread(),'$(DISTVNAME)', '$(DIST_CP)');"

distdir : create_distdir distmeta 
	$(NOECHO) $(NOOP)



# --- MakeMaker dist_test section:
disttest : distdir
	cd $(DISTVNAME) && $(ABSPERLRUN) Makefile.PL 
	cd $(DISTVNAME) && $(MAKE) $(PASTHRU)
	cd $(DISTVNAME) && $(MAKE) test $(PASTHRU)



# --- MakeMaker dist_ci section:

ci :
	$(PERLRUN) "-MExtUtils::Manifest=maniread" \
	  -e "@all = keys %{ maniread() };" \
	  -e "print(qq{Executing $(CI) @all\n}); system(qq{$(CI) @all});" \
	  -e "print(qq{Executing $(RCS_LABEL) ...\n}); system(qq{$(RCS_LABEL) @all});"


# --- MakeMaker distmeta section:
distmeta : create_distdir metafile
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{META.yml} => q{Module meta-data (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add META.yml to MANIFEST: $${'\''@'\''}\n"' --



# --- MakeMaker distsignature section:
distsignature : create_distdir
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{SIGNATURE} => q{Public-key signature (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add SIGNATURE to MANIFEST: $${'\''@'\''}\n"' --
	$(NOECHO) cd $(DISTVNAME) && $(TOUCH) SIGNATURE
	cd $(DISTVNAME) && cpansign -s



# --- MakeMaker install section:

install :: all pure_install doc_install
	$(NOECHO) $(NOOP)

install_perl :: all pure_perl_install doc_perl_install
	$(NOECHO) $(NOOP)

install_site :: all pure_site_install doc_site_install
	$(NOECHO) $(NOOP)

install_vendor :: all pure_vendor_install doc_vendor_install
	$(NOECHO) $(NOOP)

pure_install :: pure_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

doc_install :: doc_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

pure__install : pure_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

doc__install : doc_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

pure_perl_install ::
	$(NOECHO) $(MOD_INSTALL) \
		read $(PERL_ARCHLIB)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLARCHLIB)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLPRIVLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLARCHLIB) \
		$(INST_BIN) $(DESTINSTALLBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(SITEARCHEXP)/auto/$(FULLEXT)


pure_site_install ::
	$(NOECHO) $(MOD_INSTALL) \
		read $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLSITEARCH)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLSITELIB) \
		$(INST_ARCHLIB) $(DESTINSTALLSITEARCH) \
		$(INST_BIN) $(DESTINSTALLSITEBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSITESCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLSITEMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLSITEMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(PERL_ARCHLIB)/auto/$(FULLEXT)

pure_vendor_install ::
	$(NOECHO) $(MOD_INSTALL) \
		read $(VENDORARCHEXP)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLVENDORARCH)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLVENDORLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLVENDORARCH) \
		$(INST_BIN) $(DESTINSTALLVENDORBIN) \
		$(INST_SCRIPT) $(DESTINSTALLVENDORSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLVENDORMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLVENDORMAN3DIR)

doc_perl_install ::
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLARCHLIB)/perllocal.pod
	-$(NOECHO) $(MKPATH) $(DESTINSTALLARCHLIB)
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLPRIVLIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLARCHLIB)/perllocal.pod

doc_site_install ::
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLARCHLIB)/perllocal.pod
	-$(NOECHO) $(MKPATH) $(DESTINSTALLARCHLIB)
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLSITELIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLARCHLIB)/perllocal.pod

doc_vendor_install ::
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLARCHLIB)/perllocal.pod
	-$(NOECHO) $(MKPATH) $(DESTINSTALLARCHLIB)
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLVENDORLIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLARCHLIB)/perllocal.pod


uninstall :: uninstall_from_$(INSTALLDIRS)dirs
	$(NOECHO) $(NOOP)

uninstall_from_perldirs ::
	$(NOECHO) $(UNINSTALL) $(PERL_ARCHLIB)/auto/$(FULLEXT)/.packlist

uninstall_from_sitedirs ::
	$(NOECHO) $(UNINSTALL) $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist

uninstall_from_vendordirs ::
	$(NOECHO) $(UNINSTALL) $(VENDORARCHEXP)/auto/$(FULLEXT)/.packlist


# --- MakeMaker force section:
# Phony target to force checking subdirectories.
FORCE :
	$(NOECHO) $(NOOP)


# --- MakeMaker perldepend section:


# --- MakeMaker makefile section:
# We take a very conservative approach here, but it's worth it.
# We move Makefile to Makefile.old here to avoid gnu make looping.
$(FIRST_MAKEFILE) : Makefile.PL $(CONFIGDEP)
	$(NOECHO) $(ECHO) "Makefile out-of-date with respect to $?"
	$(NOECHO) $(ECHO) "Cleaning current config before rebuilding Makefile..."
	-$(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	-$(NOECHO) $(MV)   $(FIRST_MAKEFILE) $(MAKEFILE_OLD)
	- $(MAKE) $(USEMAKEFILE) $(MAKEFILE_OLD) clean $(DEV_NULL)
	$(PERLRUN) Makefile.PL 
	$(NOECHO) $(ECHO) "==> Your Makefile has been rebuilt. <=="
	$(NOECHO) $(ECHO) "==> Please rerun the $(MAKE) command.  <=="
	false



# --- MakeMaker staticmake section:

# --- MakeMaker makeaperl section ---
MAP_TARGET    = perl
FULLPERL      = /usr/bin/perl

$(MAP_TARGET) :: static $(MAKE_APERL_FILE)
	$(MAKE) $(USEMAKEFILE) $(MAKE_APERL_FILE) $@

$(MAKE_APERL_FILE) : $(FIRST_MAKEFILE) pm_to_blib
	$(NOECHO) $(ECHO) Writing \"$(MAKE_APERL_FILE)\" for this $(MAP_TARGET)
	$(NOECHO) $(PERLRUNINST) \
		Makefile.PL DIR= \
		MAKEFILE=$(MAKE_APERL_FILE) LINKTYPE=static \
		MAKEAPERL=1 NORECURS=1 CCCDLFLAGS=


# --- MakeMaker test section:

TEST_VERBOSE=0
TEST_TYPE=test_$(LINKTYPE)
TEST_FILE = test.pl
TEST_FILES = t/*.t
TESTDB_SW = -d

testdb :: testdb_$(LINKTYPE)

test :: $(TEST_TYPE) subdirs-test

subdirs-test ::
	$(NOECHO) $(NOOP)


test_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-MExtUtils::Command::MM" "-e" "test_harness($(TEST_VERBOSE), '$(INST_LIB)', '$(INST_ARCHLIB)')" $(TEST_FILES)

testdb_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) $(TESTDB_SW) "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_FILE)

test_ : test_dynamic

test_static :: test_dynamic
testdb_static :: testdb_dynamic


# --- MakeMaker ppd section:
# Creates a PPD (Perl Package Description) for a binary distribution.
ppd :
	$(NOECHO) $(ECHO) '<SOFTPKG NAME="$(DISTNAME)" VERSION="2,00,0,0">' > $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <TITLE>$(DISTNAME)</TITLE>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <ABSTRACT>Object Oriented Perl5 Interface to Network devices and MIBs through SNMP. </ABSTRACT>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <AUTHOR>Eric A. Miller &lt;emiller@cpan.org&gt;</AUTHOR>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <DEPENDENCY NAME="Math-BigInt" VERSION="0,0,0,0" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <DEPENDENCY NAME="SNMP" VERSION="0,0,0,0" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <DEPENDENCY NAME="Test-More" VERSION="0,0,0,0" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <OS NAME="$(OSNAME)" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <ARCHITECTURE NAME="i486-linux-gnu-thread-multi-5.8" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <CODEBASE HREF="" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    </IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '</SOFTPKG>' >> $(DISTNAME).ppd


# --- MakeMaker pm_to_blib section:

pm_to_blib : $(TO_INST_PM)
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', '\''$(PM_FILTER)'\'')' -- \
	  Info/Layer3/NetSNMP.pm $(INST_LIB)/SNMP/Info/Layer3/NetSNMP.pm \
	  Info/Layer2/HP.pm $(INST_LIB)/SNMP/Info/Layer2/HP.pm \
	  Info/Layer2/C2900.pm $(INST_LIB)/SNMP/Info/Layer2/C2900.pm \
	  Info/Layer2/Aruba.pm $(INST_LIB)/SNMP/Info/Layer2/Aruba.pm \
	  Info/CiscoQOS.pm $(INST_LIB)/SNMP/Info/CiscoQOS.pm \
	  Info/Layer3/Netscreen.pm $(INST_LIB)/SNMP/Info/Layer3/Netscreen.pm \
	  Info/Layer3/Sun.pm $(INST_LIB)/SNMP/Info/Layer3/Sun.pm \
	  Info/Layer3.pm $(INST_LIB)/SNMP/Info/Layer3.pm \
	  Info/Layer2/Baystack.pm $(INST_LIB)/SNMP/Info/Layer2/Baystack.pm \
	  Info.pm $(INST_LIB)/SNMP/Info.pm \
	  Info/Layer3/C4000.pm $(INST_LIB)/SNMP/Info/Layer3/C4000.pm \
	  Info/Layer2/Netgear.pm $(INST_LIB)/SNMP/Info/Layer2/Netgear.pm \
	  Info/Layer3/Cisco.pm $(INST_LIB)/SNMP/Info/Layer3/Cisco.pm \
	  Info/CiscoConfig.pm $(INST_LIB)/SNMP/Info/CiscoConfig.pm \
	  Info/Entity.pm $(INST_LIB)/SNMP/Info/Entity.pm \
	  Info/SONMP.pm $(INST_LIB)/SNMP/Info/SONMP.pm \
	  Info/Layer1/S3000.pm $(INST_LIB)/SNMP/Info/Layer1/S3000.pm \
	  Info/Layer3/Microsoft.pm $(INST_LIB)/SNMP/Info/Layer3/Microsoft.pm \
	  Info/RapidCity.pm $(INST_LIB)/SNMP/Info/RapidCity.pm \
	  Info/Layer3/HP9300.pm $(INST_LIB)/SNMP/Info/Layer3/HP9300.pm \
	  Info/Layer3/C3550.pm $(INST_LIB)/SNMP/Info/Layer3/C3550.pm \
	  Info/Layer2/ZyXEL_DSLAM.pm $(INST_LIB)/SNMP/Info/Layer2/ZyXEL_DSLAM.pm \
	  Info/Layer2/N2270.pm $(INST_LIB)/SNMP/Info/Layer2/N2270.pm \
	  Info/CiscoStpExtensions.pm $(INST_LIB)/SNMP/Info/CiscoStpExtensions.pm \
	  Info/Layer2/Allied.pm $(INST_LIB)/SNMP/Info/Layer2/Allied.pm \
	  Info/Layer2/Bay.pm $(INST_LIB)/SNMP/Info/Layer2/Bay.pm \
	  Info/Layer2.pm $(INST_LIB)/SNMP/Info/Layer2.pm \
	  Info/Layer3/Passport.pm $(INST_LIB)/SNMP/Info/Layer3/Passport.pm \
	  Info/Layer2/Catalyst.pm $(INST_LIB)/SNMP/Info/Layer2/Catalyst.pm \
	  Info/Layer3/Extreme.pm $(INST_LIB)/SNMP/Info/Layer3/Extreme.pm \
	  Info/CiscoVTP.pm $(INST_LIB)/SNMP/Info/CiscoVTP.pm \
	  Info/IEEE802dot11.pm $(INST_LIB)/SNMP/Info/IEEE802dot11.pm \
	  Info/Layer2/Airespace.pm $(INST_LIB)/SNMP/Info/Layer2/Airespace.pm \
	  Info/FDP.pm $(INST_LIB)/SNMP/Info/FDP.pm \
	  Info/Layer2/Orinoco.pm $(INST_LIB)/SNMP/Info/Layer2/Orinoco.pm \
	  Info/Layer3/Contivity.pm $(INST_LIB)/SNMP/Info/Layer3/Contivity.pm \
	  Info/Layer3/AlcatelLucent.pm $(INST_LIB)/SNMP/Info/Layer3/AlcatelLucent.pm \
	  Info/Layer3/BayRS.pm $(INST_LIB)/SNMP/Info/Layer3/BayRS.pm \
	  Info/Layer3/C6500.pm $(INST_LIB)/SNMP/Info/Layer3/C6500.pm \
	  Info/CiscoRTT.pm $(INST_LIB)/SNMP/Info/CiscoRTT.pm \
	  Info/CiscoPower.pm $(INST_LIB)/SNMP/Info/CiscoPower.pm \
	  Info/NortelStack.pm $(INST_LIB)/SNMP/Info/NortelStack.pm \
	  Info/LLDP.pm $(INST_LIB)/SNMP/Info/LLDP.pm \
	  Info/CiscoStats.pm $(INST_LIB)/SNMP/Info/CiscoStats.pm \
	  Info/Layer1.pm $(INST_LIB)/SNMP/Info/Layer1.pm \
	  Info/Layer1/Allied.pm $(INST_LIB)/SNMP/Info/Layer1/Allied.pm \
	  Info/CDP.pm $(INST_LIB)/SNMP/Info/CDP.pm \
	  Info/MAU.pm $(INST_LIB)/SNMP/Info/MAU.pm \
	  Info/Layer1/Asante.pm $(INST_LIB)/SNMP/Info/Layer1/Asante.pm \
	  Info/Layer2/C1900.pm $(INST_LIB)/SNMP/Info/Layer2/C1900.pm \
	  Info/Bridge.pm $(INST_LIB)/SNMP/Info/Bridge.pm \
	  Info/Layer3/N1600.pm $(INST_LIB)/SNMP/Info/Layer3/N1600.pm \
	  Info/EtherLike.pm $(INST_LIB)/SNMP/Info/EtherLike.pm \
	  Info/Layer1/Cyclades.pm $(INST_LIB)/SNMP/Info/Layer1/Cyclades.pm \
	  Info/Layer2/NAP222x.pm $(INST_LIB)/SNMP/Info/Layer2/NAP222x.pm \
	  Info/Layer2/Foundry.pm $(INST_LIB)/SNMP/Info/Layer2/Foundry.pm \
	  Info/PowerEthernet.pm $(INST_LIB)/SNMP/Info/PowerEthernet.pm \
	  Info/CiscoStack.pm $(INST_LIB)/SNMP/Info/CiscoStack.pm \
	  Info/Layer2/Centillion.pm $(INST_LIB)/SNMP/Info/Layer2/Centillion.pm \
	  Info/Layer3/Enterasys.pm $(INST_LIB)/SNMP/Info/Layer3/Enterasys.pm \
	  Info/Layer3/Dell.pm $(INST_LIB)/SNMP/Info/Layer3/Dell.pm \
	  Info/Airespace.pm $(INST_LIB)/SNMP/Info/Airespace.pm \
	  Info/CiscoImage.pm $(INST_LIB)/SNMP/Info/CiscoImage.pm \
	  Info/CiscoPortSecurity.pm $(INST_LIB)/SNMP/Info/CiscoPortSecurity.pm \
	  Info/Layer3/Juniper.pm $(INST_LIB)/SNMP/Info/Layer3/Juniper.pm \
	  Info/Layer3/Timetra.pm $(INST_LIB)/SNMP/Info/Layer3/Timetra.pm \
	  Info/Layer3/Foundry.pm $(INST_LIB)/SNMP/Info/Layer3/Foundry.pm \
	  Info/Layer2/Cisco.pm $(INST_LIB)/SNMP/Info/Layer2/Cisco.pm \
	  Info/Layer3/AlteonAD.pm $(INST_LIB)/SNMP/Info/Layer3/AlteonAD.pm \
	  Info/Layer3/Aironet.pm $(INST_LIB)/SNMP/Info/Layer3/Aironet.pm \
	  Info/Layer1/Bayhub.pm $(INST_LIB)/SNMP/Info/Layer1/Bayhub.pm \
	  Info/Layer2/Aironet.pm $(INST_LIB)/SNMP/Info/Layer2/Aironet.pm 
	$(NOECHO) $(TOUCH) pm_to_blib


# --- MakeMaker selfdocument section:


# --- MakeMaker postamble section:

.PHONY: readme
readme: README
README: Info.pm
	pod2text -l Info.pm > README

# End.
